### ISSUE TITLE
Apple M2 cpus not optimized

### ISSUE THREAD

**Issue by MartinOndejka** [o1-labs/o1js-bindings#166]
[Fix here](https://github.com/o1-labs/o1js-bindings/blob/main/js/node/node-backend.js#L144) doesn't catch all of the M2 cpus, like `Apple M2 Pro` etc. I would fix it myself, but I don't know where did those numbers come from.

**Comment by mitschabaude** [comment]
Oh nice catch @MartinOndejka! The numbers came from testing which number of CPUs was the fastest

**Comment by mitschabaude** [comment]
Feel free to test proof generation on your machine and put the best-performing number there!

**Comment by jackryanservia** [comment]
Fixed permanently in o1-labs/o1js#1456 :)
